@file:Suppress("DuplicatedCode")

package io.layercraft.packetlib.codec

object MinecraftCodecs {

    val V1_19_3: Codec =
        codec(ProtocolVersion.V1_19_3) {
            packets(PacketState.HANDSHAKING) {
                serverBound(0x00, io.layercraft.packetlib.packets.v1_19_3.handshaking.serverbound.SetProtocolPacket::class, io.layercraft.packetlib.packets.v1_19_3.handshaking.serverbound.SetProtocolPacket)
                serverBound(0xfe, io.layercraft.packetlib.packets.v1_19_3.handshaking.serverbound.LegacyServerListPingPacket::class, io.layercraft.packetlib.packets.v1_19_3.handshaking.serverbound.LegacyServerListPingPacket)
            }

            packets(PacketState.LOGIN) {
                clientBound(0x00, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.DisconnectPacket::class, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.DisconnectPacket)
                clientBound(0x01, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.EncryptionBeginPacket::class, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.EncryptionBeginPacket)
                clientBound(0x02, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.SuccessPacket::class, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.SuccessPacket)
                clientBound(0x03, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.CompressPacket::class, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.CompressPacket)
                clientBound(0x04, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.LoginPluginRequestPacket::class, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.LoginPluginRequestPacket)
                serverBound(0x00, io.layercraft.packetlib.packets.v1_19_3.login.serverbound.LoginStartPacket::class, io.layercraft.packetlib.packets.v1_19_3.login.serverbound.LoginStartPacket)
                serverBound(0x01, io.layercraft.packetlib.packets.v1_19_3.login.serverbound.EncryptionBeginPacket::class, io.layercraft.packetlib.packets.v1_19_3.login.serverbound.EncryptionBeginPacket)
                serverBound(0x02, io.layercraft.packetlib.packets.v1_19_3.login.serverbound.LoginPluginResponsePacket::class, io.layercraft.packetlib.packets.v1_19_3.login.serverbound.LoginPluginResponsePacket)
            }

            packets(PacketState.STATUS) {
                clientBound(0x00, io.layercraft.packetlib.packets.v1_19_3.status.clientbound.ServerInfoPacket::class, io.layercraft.packetlib.packets.v1_19_3.status.clientbound.ServerInfoPacket)
                clientBound(0x01, io.layercraft.packetlib.packets.v1_19_3.status.clientbound.PingPacket::class, io.layercraft.packetlib.packets.v1_19_3.status.clientbound.PingPacket)
                serverBound(0x00, io.layercraft.packetlib.packets.v1_19_3.status.serverbound.PingStartPacket::class, io.layercraft.packetlib.packets.v1_19_3.status.serverbound.PingStartPacket)
                serverBound(0x01, io.layercraft.packetlib.packets.v1_19_3.status.serverbound.PingPacket::class, io.layercraft.packetlib.packets.v1_19_3.status.serverbound.PingPacket)
            }

            packets(PacketState.PLAY) {
                clientBound(0x00, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SpawnEntityPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SpawnEntityPacket)
                clientBound(0x01, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SpawnEntityExperienceOrbPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SpawnEntityExperienceOrbPacket)
                clientBound(0x02, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.NamedEntitySpawnPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.NamedEntitySpawnPacket)
                clientBound(0x03, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AnimationPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AnimationPacket)
                clientBound(0x04, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.StatisticsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.StatisticsPacket)
                clientBound(0x05, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AcknowledgePlayerDiggingPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AcknowledgePlayerDiggingPacket)
                clientBound(0x06, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.BlockBreakAnimationPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.BlockBreakAnimationPacket)
                clientBound(0x07, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TileEntityDataPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TileEntityDataPacket)
                clientBound(0x08, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.BlockActionPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.BlockActionPacket)
                clientBound(0x09, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.BlockChangePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.BlockChangePacket)
                clientBound(0x0a, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.BossBarPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.BossBarPacket)
                clientBound(0x0b, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.DifficultyPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.DifficultyPacket)
                clientBound(0x0c, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ClearTitlesPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ClearTitlesPacket)
                clientBound(0x0d, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TabCompletePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TabCompletePacket)
                clientBound(0x0e, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.DeclareCommandsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.DeclareCommandsPacket)
                clientBound(0x0f, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CloseWindowPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CloseWindowPacket)
                clientBound(0x10, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WindowItemsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WindowItemsPacket)
                clientBound(0x11, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CraftProgressBarPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CraftProgressBarPacket)
                clientBound(0x12, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetSlotPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetSlotPacket)
                clientBound(0x13, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetCooldownPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetCooldownPacket)
                clientBound(0x14, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ChatSuggestionsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ChatSuggestionsPacket)
                clientBound(0x15, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CustomPayloadPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CustomPayloadPacket)
                clientBound(0x17, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.KickDisconnectPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.KickDisconnectPacket)
                clientBound(0x18, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ProfilelessChatPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ProfilelessChatPacket)
                clientBound(0x19, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityStatusPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityStatusPacket)
                clientBound(0x1a, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ExplosionPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ExplosionPacket)
                clientBound(0x1b, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UnloadChunkPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UnloadChunkPacket)
                clientBound(0x1c, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.GameStateChangePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.GameStateChangePacket)
                clientBound(0x1d, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.OpenHorseWindowPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.OpenHorseWindowPacket)
                clientBound(0x1e, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.InitializeWorldBorderPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.InitializeWorldBorderPacket)
                clientBound(0x1f, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.KeepAlivePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.KeepAlivePacket)
                clientBound(0x20, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.MapChunkPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.MapChunkPacket)
                clientBound(0x21, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldEventPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldEventPacket)
                clientBound(0x22, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldParticlesPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldParticlesPacket)
                clientBound(0x23, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateLightPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateLightPacket)
                clientBound(0x24, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.LoginPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.LoginPacket)
                clientBound(0x25, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.MapPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.MapPacket)
                clientBound(0x26, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TradeListPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TradeListPacket)
                clientBound(0x27, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.RelEntityMovePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.RelEntityMovePacket)
                clientBound(0x28, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityMoveLookPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityMoveLookPacket)
                clientBound(0x29, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityLookPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityLookPacket)
                clientBound(0x2a, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.VehicleMovePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.VehicleMovePacket)
                clientBound(0x2b, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.OpenBookPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.OpenBookPacket)
                clientBound(0x2c, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.OpenWindowPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.OpenWindowPacket)
                clientBound(0x2d, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.OpenSignEntityPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.OpenSignEntityPacket)
                clientBound(0x2e, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.PingPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.PingPacket)
                clientBound(0x2f, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CraftRecipeResponsePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CraftRecipeResponsePacket)
                clientBound(0x30, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AbilitiesPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AbilitiesPacket)
                clientBound(0x32, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EndCombatEventPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EndCombatEventPacket)
                clientBound(0x33, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EnterCombatEventPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EnterCombatEventPacket)
                clientBound(0x34, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.DeathCombatEventPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.DeathCombatEventPacket)
                clientBound(0x35, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.PlayerRemovePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.PlayerRemovePacket)
                clientBound(0x37, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.FacePlayerPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.FacePlayerPacket)
                clientBound(0x38, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.PositionPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.PositionPacket)
                clientBound(0x39, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UnlockRecipesPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UnlockRecipesPacket)
                clientBound(0x3a, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityDestroyPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityDestroyPacket)
                clientBound(0x3b, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.RemoveEntityEffectPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.RemoveEntityEffectPacket)
                clientBound(0x3c, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ResourcePackSendPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ResourcePackSendPacket)
                clientBound(0x3d, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.RespawnPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.RespawnPacket)
                clientBound(0x3e, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityHeadRotationPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityHeadRotationPacket)
                clientBound(0x3f, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.MultiBlockChangePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.MultiBlockChangePacket)
                clientBound(0x40, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SelectAdvancementTabPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SelectAdvancementTabPacket)
                clientBound(0x41, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ServerDataPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ServerDataPacket)
                clientBound(0x42, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ActionBarPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ActionBarPacket)
                clientBound(0x43, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderCenterPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderCenterPacket)
                clientBound(0x44, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderLerpSizePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderLerpSizePacket)
                clientBound(0x45, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderSizePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderSizePacket)
                clientBound(0x46, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderWarningDelayPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderWarningDelayPacket)
                clientBound(0x47, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderWarningReachPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderWarningReachPacket)
                clientBound(0x48, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CameraPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CameraPacket)
                clientBound(0x49, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.HeldItemSlotPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.HeldItemSlotPacket)
                clientBound(0x4a, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateViewPositionPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateViewPositionPacket)
                clientBound(0x4b, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateViewDistancePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateViewDistancePacket)
                clientBound(0x4c, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SpawnPositionPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SpawnPositionPacket)
                clientBound(0x4d, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ScoreboardDisplayObjectivePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ScoreboardDisplayObjectivePacket)
                clientBound(0x4e, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityMetadataPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityMetadataPacket)
                clientBound(0x4f, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AttachEntityPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AttachEntityPacket)
                clientBound(0x50, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityVelocityPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityVelocityPacket)
                clientBound(0x51, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityEquipmentPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityEquipmentPacket)
                clientBound(0x52, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ExperiencePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ExperiencePacket)
                clientBound(0x53, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateHealthPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateHealthPacket)
                clientBound(0x54, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ScoreboardObjectivePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ScoreboardObjectivePacket)
                clientBound(0x55, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetPassengersPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetPassengersPacket)
                clientBound(0x56, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TeamsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TeamsPacket)
                clientBound(0x57, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ScoreboardScorePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ScoreboardScorePacket)
                clientBound(0x58, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SimulationDistancePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SimulationDistancePacket)
                clientBound(0x59, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetTitleSubtitlePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetTitleSubtitlePacket)
                clientBound(0x5a, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateTimePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateTimePacket)
                clientBound(0x5b, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetTitleTextPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetTitleTextPacket)
                clientBound(0x5c, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetTitleTimePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetTitleTimePacket)
                clientBound(0x5d, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntitySoundEffectPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntitySoundEffectPacket)
                clientBound(0x5e, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SoundEffectPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SoundEffectPacket)
                clientBound(0x5f, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.StopSoundPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.StopSoundPacket)
                clientBound(0x60, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SystemChatPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SystemChatPacket)
                clientBound(0x61, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.PlayerlistHeaderPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.PlayerlistHeaderPacket)
                clientBound(0x62, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.NbtQueryResponsePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.NbtQueryResponsePacket)
                clientBound(0x63, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CollectPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CollectPacket)
                clientBound(0x64, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityTeleportPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityTeleportPacket)
                clientBound(0x65, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AdvancementsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AdvancementsPacket)
                clientBound(0x66, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityUpdateAttributesPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityUpdateAttributesPacket)
                clientBound(0x67, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.FeatureFlagsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.FeatureFlagsPacket)
                clientBound(0x68, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityEffectPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityEffectPacket)
                clientBound(0x6a, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TagsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TagsPacket)
                serverBound(0x00, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.TeleportConfirmPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.TeleportConfirmPacket)
                serverBound(0x01, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.QueryBlockNbtPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.QueryBlockNbtPacket)
                serverBound(0x02, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SetDifficultyPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SetDifficultyPacket)
                serverBound(0x03, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.MessageAcknowledgementPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.MessageAcknowledgementPacket)
                serverBound(0x06, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.ClientCommandPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.ClientCommandPacket)
                serverBound(0x07, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SettingsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SettingsPacket)
                serverBound(0x08, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.TabCompletePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.TabCompletePacket)
                serverBound(0x09, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.EnchantItemPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.EnchantItemPacket)
                serverBound(0x0a, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.WindowClickPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.WindowClickPacket)
                serverBound(0x0b, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.CloseWindowPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.CloseWindowPacket)
                serverBound(0x0c, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.CustomPayloadPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.CustomPayloadPacket)
                serverBound(0x0d, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.EditBookPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.EditBookPacket)
                serverBound(0x0e, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.QueryEntityNbtPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.QueryEntityNbtPacket)
                serverBound(0x0f, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UseEntityPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UseEntityPacket)
                serverBound(0x10, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.GenerateStructurePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.GenerateStructurePacket)
                serverBound(0x11, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.KeepAlivePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.KeepAlivePacket)
                serverBound(0x12, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.LockDifficultyPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.LockDifficultyPacket)
                serverBound(0x13, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.PositionPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.PositionPacket)
                serverBound(0x14, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.PositionLookPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.PositionLookPacket)
                serverBound(0x15, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.LookPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.LookPacket)
                serverBound(0x16, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.FlyingPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.FlyingPacket)
                serverBound(0x17, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.VehicleMovePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.VehicleMovePacket)
                serverBound(0x18, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SteerBoatPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SteerBoatPacket)
                serverBound(0x19, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.PickItemPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.PickItemPacket)
                serverBound(0x1a, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.CraftRecipeRequestPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.CraftRecipeRequestPacket)
                serverBound(0x1b, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.AbilitiesPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.AbilitiesPacket)
                serverBound(0x1c, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.BlockDigPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.BlockDigPacket)
                serverBound(0x1d, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.EntityActionPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.EntityActionPacket)
                serverBound(0x1e, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SteerVehiclePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SteerVehiclePacket)
                serverBound(0x1f, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.PongPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.PongPacket)
                serverBound(0x20, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.ChatSessionUpdatePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.ChatSessionUpdatePacket)
                serverBound(0x21, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.RecipeBookPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.RecipeBookPacket)
                serverBound(0x22, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.DisplayedRecipePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.DisplayedRecipePacket)
                serverBound(0x23, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.NameItemPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.NameItemPacket)
                serverBound(0x24, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.ResourcePackReceivePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.ResourcePackReceivePacket)
                serverBound(0x25, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.AdvancementTabPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.AdvancementTabPacket)
                serverBound(0x26, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SelectTradePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SelectTradePacket)
                serverBound(0x27, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SetBeaconEffectPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SetBeaconEffectPacket)
                serverBound(0x28, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.HeldItemSlotPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.HeldItemSlotPacket)
                serverBound(0x29, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateCommandBlockPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateCommandBlockPacket)
                serverBound(0x2a, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateCommandBlockMinecartPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateCommandBlockMinecartPacket)
                serverBound(0x2b, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SetCreativeSlotPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SetCreativeSlotPacket)
                serverBound(0x2c, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateJigsawBlockPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateJigsawBlockPacket)
                serverBound(0x2d, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateStructureBlockPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateStructureBlockPacket)
                serverBound(0x2e, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateSignPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateSignPacket)
                serverBound(0x2f, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.ArmAnimationPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.ArmAnimationPacket)
                serverBound(0x30, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SpectatePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SpectatePacket)
                serverBound(0x31, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.BlockPlacePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.BlockPlacePacket)
                serverBound(0x32, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UseItemPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UseItemPacket)
            }
        }

    val V1_19_4: Codec = codecCopy(ProtocolVersion.V1_19_4, this.V1_19_3)
}