@file:Suppress("DuplicatedCode")

package io.layercraft.packetlib.codec

import io.layercraft.packetlib.data.ProtocolVersion
import io.layercraft.packetlib.packets.PacketState

object MinecraftCodecs {
    val V1_19_2: MinecraftCodec =
        MinecraftCodec.create(ProtocolVersion.V1_19_2)
            .registerPacketRegistry(
                PacketState.HANDSHAKING,
                MinecraftCodecRegistry.create()
                    .registerServerBoundPacket(0x00, io.layercraft.packetlib.packets.v1_19_2.handshaking.serverbound.SetProtocolPacket::class, io.layercraft.packetlib.packets.v1_19_2.handshaking.serverbound.SetProtocolPacket)
                    .registerServerBoundPacket(0xfe, io.layercraft.packetlib.packets.v1_19_2.handshaking.serverbound.LegacyServerListPingPacket::class, io.layercraft.packetlib.packets.v1_19_2.handshaking.serverbound.LegacyServerListPingPacket),
            )
            .registerPacketRegistry(
                PacketState.LOGIN,
                MinecraftCodecRegistry.create()
                    .registerClientBoundPacket(0x00, io.layercraft.packetlib.packets.v1_19_2.login.clientbound.DisconnectPacket::class, io.layercraft.packetlib.packets.v1_19_2.login.clientbound.DisconnectPacket)
                    .registerClientBoundPacket(0x01, io.layercraft.packetlib.packets.v1_19_2.login.clientbound.EncryptionBeginPacket::class, io.layercraft.packetlib.packets.v1_19_2.login.clientbound.EncryptionBeginPacket)
                    .registerClientBoundPacket(0x02, io.layercraft.packetlib.packets.v1_19_2.login.clientbound.SuccessPacket::class, io.layercraft.packetlib.packets.v1_19_2.login.clientbound.SuccessPacket)
                    .registerClientBoundPacket(0x03, io.layercraft.packetlib.packets.v1_19_2.login.clientbound.CompressPacket::class, io.layercraft.packetlib.packets.v1_19_2.login.clientbound.CompressPacket)
                    .registerClientBoundPacket(0x04, io.layercraft.packetlib.packets.v1_19_2.login.clientbound.LoginPluginRequestPacket::class, io.layercraft.packetlib.packets.v1_19_2.login.clientbound.LoginPluginRequestPacket)
                    .registerServerBoundPacket(0x00, io.layercraft.packetlib.packets.v1_19_2.login.serverbound.LoginStartPacket::class, io.layercraft.packetlib.packets.v1_19_2.login.serverbound.LoginStartPacket)
                    .registerServerBoundPacket(0x01, io.layercraft.packetlib.packets.v1_19_2.login.serverbound.EncryptionBeginPacket::class, io.layercraft.packetlib.packets.v1_19_2.login.serverbound.EncryptionBeginPacket)
                    .registerServerBoundPacket(0x02, io.layercraft.packetlib.packets.v1_19_2.login.serverbound.LoginPluginResponsePacket::class, io.layercraft.packetlib.packets.v1_19_2.login.serverbound.LoginPluginResponsePacket),
            )
            .registerPacketRegistry(
                PacketState.STATUS,
                MinecraftCodecRegistry.create()
                    .registerClientBoundPacket(0x00, io.layercraft.packetlib.packets.v1_19_2.status.clientbound.ServerInfoPacket::class, io.layercraft.packetlib.packets.v1_19_2.status.clientbound.ServerInfoPacket)
                    .registerClientBoundPacket(0x01, io.layercraft.packetlib.packets.v1_19_2.status.clientbound.PingPacket::class, io.layercraft.packetlib.packets.v1_19_2.status.clientbound.PingPacket)
                    .registerServerBoundPacket(0x00, io.layercraft.packetlib.packets.v1_19_2.status.serverbound.PingStartPacket::class, io.layercraft.packetlib.packets.v1_19_2.status.serverbound.PingStartPacket)
                    .registerServerBoundPacket(0x01, io.layercraft.packetlib.packets.v1_19_2.status.serverbound.PingPacket::class, io.layercraft.packetlib.packets.v1_19_2.status.serverbound.PingPacket),
            )
            .registerPacketRegistry(
                PacketState.PLAY,
                MinecraftCodecRegistry.create()
                    .registerClientBoundPacket(0x00, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SpawnEntityPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SpawnEntityPacket)
                    .registerClientBoundPacket(0x01, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SpawnEntityExperienceOrbPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SpawnEntityExperienceOrbPacket)
                    .registerClientBoundPacket(0x02, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.NamedEntitySpawnPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.NamedEntitySpawnPacket)
                    .registerClientBoundPacket(0x03, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.AnimationPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.AnimationPacket)
                    .registerClientBoundPacket(0x04, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.StatisticsPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.StatisticsPacket)
                    .registerClientBoundPacket(0x05, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.AcknowledgePlayerDiggingPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.AcknowledgePlayerDiggingPacket)
                    .registerClientBoundPacket(0x06, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.BlockBreakAnimationPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.BlockBreakAnimationPacket)
                    .registerClientBoundPacket(0x07, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.TileEntityDataPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.TileEntityDataPacket)
                    .registerClientBoundPacket(0x08, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.BlockActionPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.BlockActionPacket)
                    .registerClientBoundPacket(0x09, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.BlockChangePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.BlockChangePacket)
                    .registerClientBoundPacket(0x0a, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.BossBarPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.BossBarPacket)
                    .registerClientBoundPacket(0x0b, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.DifficultyPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.DifficultyPacket)
                    .registerClientBoundPacket(0x0c, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ChatPreviewPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ChatPreviewPacket)
                    .registerClientBoundPacket(0x0d, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ClearTitlesPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ClearTitlesPacket)
                    .registerClientBoundPacket(0x0e, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.TabCompletePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.TabCompletePacket)
                    .registerClientBoundPacket(0x0f, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.DeclareCommandsPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.DeclareCommandsPacket)
                    .registerClientBoundPacket(0x10, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.CloseWindowPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.CloseWindowPacket)
                    .registerClientBoundPacket(0x11, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.WindowItemsPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.WindowItemsPacket)
                    .registerClientBoundPacket(0x12, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.CraftProgressBarPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.CraftProgressBarPacket)
                    .registerClientBoundPacket(0x13, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SetSlotPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SetSlotPacket)
                    .registerClientBoundPacket(0x14, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SetCooldownPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SetCooldownPacket)
                    .registerClientBoundPacket(0x15, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ChatSuggestionsPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ChatSuggestionsPacket)
                    .registerClientBoundPacket(0x16, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.CustomPayloadPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.CustomPayloadPacket)
                    .registerClientBoundPacket(0x17, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.NamedSoundEffectPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.NamedSoundEffectPacket)
                    .registerClientBoundPacket(0x18, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.HideMessagePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.HideMessagePacket)
                    .registerClientBoundPacket(0x19, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.KickDisconnectPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.KickDisconnectPacket)
                    .registerClientBoundPacket(0x1a, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityStatusPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityStatusPacket)
                    .registerClientBoundPacket(0x1b, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ExplosionPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ExplosionPacket)
                    .registerClientBoundPacket(0x1c, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.UnloadChunkPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.UnloadChunkPacket)
                    .registerClientBoundPacket(0x1d, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.GameStateChangePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.GameStateChangePacket)
                    .registerClientBoundPacket(0x1e, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.OpenHorseWindowPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.OpenHorseWindowPacket)
                    .registerClientBoundPacket(0x1f, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.InitializeWorldBorderPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.InitializeWorldBorderPacket)
                    .registerClientBoundPacket(0x20, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.KeepAlivePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.KeepAlivePacket)
                    .registerClientBoundPacket(0x21, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.MapChunkPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.MapChunkPacket)
                    .registerClientBoundPacket(0x22, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.WorldEventPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.WorldEventPacket)
                    .registerClientBoundPacket(0x23, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.WorldParticlesPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.WorldParticlesPacket)
                    .registerClientBoundPacket(0x24, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.UpdateLightPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.UpdateLightPacket)
                    .registerClientBoundPacket(0x25, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.LoginPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.LoginPacket)
                    .registerClientBoundPacket(0x26, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.MapPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.MapPacket)
                    .registerClientBoundPacket(0x27, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.TradeListPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.TradeListPacket)
                    .registerClientBoundPacket(0x28, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.RelEntityMovePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.RelEntityMovePacket)
                    .registerClientBoundPacket(0x29, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityMoveLookPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityMoveLookPacket)
                    .registerClientBoundPacket(0x2a, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityLookPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityLookPacket)
                    .registerClientBoundPacket(0x2b, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.VehicleMovePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.VehicleMovePacket)
                    .registerClientBoundPacket(0x2c, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.OpenBookPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.OpenBookPacket)
                    .registerClientBoundPacket(0x2d, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.OpenWindowPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.OpenWindowPacket)
                    .registerClientBoundPacket(0x2e, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.OpenSignEntityPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.OpenSignEntityPacket)
                    .registerClientBoundPacket(0x2f, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.PingPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.PingPacket)
                    .registerClientBoundPacket(0x30, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.CraftRecipeResponsePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.CraftRecipeResponsePacket)
                    .registerClientBoundPacket(0x31, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.AbilitiesPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.AbilitiesPacket)
                    .registerClientBoundPacket(0x34, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EndCombatEventPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EndCombatEventPacket)
                    .registerClientBoundPacket(0x35, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EnterCombatEventPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EnterCombatEventPacket)
                    .registerClientBoundPacket(0x36, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.DeathCombatEventPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.DeathCombatEventPacket)
                    .registerClientBoundPacket(0x37, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.PlayerInfoPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.PlayerInfoPacket)
                    .registerClientBoundPacket(0x38, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.FacePlayerPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.FacePlayerPacket)
                    .registerClientBoundPacket(0x39, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.PositionPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.PositionPacket)
                    .registerClientBoundPacket(0x3a, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.UnlockRecipesPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.UnlockRecipesPacket)
                    .registerClientBoundPacket(0x3b, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityDestroyPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityDestroyPacket)
                    .registerClientBoundPacket(0x3c, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.RemoveEntityEffectPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.RemoveEntityEffectPacket)
                    .registerClientBoundPacket(0x3d, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ResourcePackSendPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ResourcePackSendPacket)
                    .registerClientBoundPacket(0x3e, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.RespawnPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.RespawnPacket)
                    .registerClientBoundPacket(0x3f, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityHeadRotationPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityHeadRotationPacket)
                    .registerClientBoundPacket(0x40, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.MultiBlockChangePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.MultiBlockChangePacket)
                    .registerClientBoundPacket(0x41, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SelectAdvancementTabPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SelectAdvancementTabPacket)
                    .registerClientBoundPacket(0x42, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ServerDataPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ServerDataPacket)
                    .registerClientBoundPacket(0x43, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ActionBarPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ActionBarPacket)
                    .registerClientBoundPacket(0x44, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.WorldBorderCenterPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.WorldBorderCenterPacket)
                    .registerClientBoundPacket(0x45, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.WorldBorderLerpSizePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.WorldBorderLerpSizePacket)
                    .registerClientBoundPacket(0x46, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.WorldBorderSizePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.WorldBorderSizePacket)
                    .registerClientBoundPacket(0x47, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.WorldBorderWarningDelayPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.WorldBorderWarningDelayPacket)
                    .registerClientBoundPacket(0x48, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.WorldBorderWarningReachPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.WorldBorderWarningReachPacket)
                    .registerClientBoundPacket(0x49, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.CameraPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.CameraPacket)
                    .registerClientBoundPacket(0x4a, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.HeldItemSlotPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.HeldItemSlotPacket)
                    .registerClientBoundPacket(0x4b, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.UpdateViewPositionPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.UpdateViewPositionPacket)
                    .registerClientBoundPacket(0x4c, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.UpdateViewDistancePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.UpdateViewDistancePacket)
                    .registerClientBoundPacket(0x4d, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SpawnPositionPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SpawnPositionPacket)
                    .registerClientBoundPacket(0x4e, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ShouldDisplayChatPreviewPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ShouldDisplayChatPreviewPacket)
                    .registerClientBoundPacket(0x4f, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ScoreboardDisplayObjectivePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ScoreboardDisplayObjectivePacket)
                    .registerClientBoundPacket(0x50, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityMetadataPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityMetadataPacket)
                    .registerClientBoundPacket(0x51, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.AttachEntityPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.AttachEntityPacket)
                    .registerClientBoundPacket(0x52, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityVelocityPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityVelocityPacket)
                    .registerClientBoundPacket(0x53, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityEquipmentPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityEquipmentPacket)
                    .registerClientBoundPacket(0x54, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ExperiencePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ExperiencePacket)
                    .registerClientBoundPacket(0x55, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.UpdateHealthPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.UpdateHealthPacket)
                    .registerClientBoundPacket(0x56, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ScoreboardObjectivePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ScoreboardObjectivePacket)
                    .registerClientBoundPacket(0x57, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SetPassengersPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SetPassengersPacket)
                    .registerClientBoundPacket(0x58, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.TeamsPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.TeamsPacket)
                    .registerClientBoundPacket(0x59, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ScoreboardScorePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.ScoreboardScorePacket)
                    .registerClientBoundPacket(0x5a, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SimulationDistancePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SimulationDistancePacket)
                    .registerClientBoundPacket(0x5b, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SetTitleSubtitlePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SetTitleSubtitlePacket)
                    .registerClientBoundPacket(0x5c, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.UpdateTimePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.UpdateTimePacket)
                    .registerClientBoundPacket(0x5d, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SetTitleTextPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SetTitleTextPacket)
                    .registerClientBoundPacket(0x5e, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SetTitleTimePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SetTitleTimePacket)
                    .registerClientBoundPacket(0x5f, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntitySoundEffectPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntitySoundEffectPacket)
                    .registerClientBoundPacket(0x60, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SoundEffectPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SoundEffectPacket)
                    .registerClientBoundPacket(0x61, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.StopSoundPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.StopSoundPacket)
                    .registerClientBoundPacket(0x62, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SystemChatPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.SystemChatPacket)
                    .registerClientBoundPacket(0x63, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.PlayerlistHeaderPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.PlayerlistHeaderPacket)
                    .registerClientBoundPacket(0x64, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.NbtQueryResponsePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.NbtQueryResponsePacket)
                    .registerClientBoundPacket(0x65, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.CollectPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.CollectPacket)
                    .registerClientBoundPacket(0x66, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityTeleportPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityTeleportPacket)
                    .registerClientBoundPacket(0x67, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.AdvancementsPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.AdvancementsPacket)
                    .registerClientBoundPacket(0x68, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityUpdateAttributesPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityUpdateAttributesPacket)
                    .registerClientBoundPacket(0x69, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityEffectPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.EntityEffectPacket)
                    .registerClientBoundPacket(0x6a, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.DeclareRecipesPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.DeclareRecipesPacket)
                    .registerClientBoundPacket(0x6b, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.TagsPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.clientbound.TagsPacket)
                    .registerServerBoundPacket(0x00, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.TeleportConfirmPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.TeleportConfirmPacket)
                    .registerServerBoundPacket(0x01, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.QueryBlockNbtPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.QueryBlockNbtPacket)
                    .registerServerBoundPacket(0x02, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.SetDifficultyPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.SetDifficultyPacket)
                    .registerServerBoundPacket(0x03, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.MessageAcknowledgementPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.MessageAcknowledgementPacket)
                    .registerServerBoundPacket(0x04, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.ChatCommandPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.ChatCommandPacket)
                    .registerServerBoundPacket(0x05, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.ChatMessagePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.ChatMessagePacket)
                    .registerServerBoundPacket(0x06, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.ChatPreviewPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.ChatPreviewPacket)
                    .registerServerBoundPacket(0x07, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.ClientCommandPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.ClientCommandPacket)
                    .registerServerBoundPacket(0x08, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.SettingsPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.SettingsPacket)
                    .registerServerBoundPacket(0x09, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.TabCompletePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.TabCompletePacket)
                    .registerServerBoundPacket(0x0a, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.EnchantItemPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.EnchantItemPacket)
                    .registerServerBoundPacket(0x0b, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.WindowClickPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.WindowClickPacket)
                    .registerServerBoundPacket(0x0c, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.CloseWindowPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.CloseWindowPacket)
                    .registerServerBoundPacket(0x0d, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.CustomPayloadPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.CustomPayloadPacket)
                    .registerServerBoundPacket(0x0e, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.EditBookPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.EditBookPacket)
                    .registerServerBoundPacket(0x0f, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.QueryEntityNbtPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.QueryEntityNbtPacket)
                    .registerServerBoundPacket(0x10, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.UseEntityPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.UseEntityPacket)
                    .registerServerBoundPacket(0x11, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.GenerateStructurePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.GenerateStructurePacket)
                    .registerServerBoundPacket(0x12, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.KeepAlivePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.KeepAlivePacket)
                    .registerServerBoundPacket(0x13, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.LockDifficultyPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.LockDifficultyPacket)
                    .registerServerBoundPacket(0x14, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.PositionPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.PositionPacket)
                    .registerServerBoundPacket(0x15, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.PositionLookPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.PositionLookPacket)
                    .registerServerBoundPacket(0x16, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.LookPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.LookPacket)
                    .registerServerBoundPacket(0x17, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.FlyingPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.FlyingPacket)
                    .registerServerBoundPacket(0x18, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.VehicleMovePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.VehicleMovePacket)
                    .registerServerBoundPacket(0x19, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.SteerBoatPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.SteerBoatPacket)
                    .registerServerBoundPacket(0x1a, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.PickItemPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.PickItemPacket)
                    .registerServerBoundPacket(0x1b, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.CraftRecipeRequestPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.CraftRecipeRequestPacket)
                    .registerServerBoundPacket(0x1c, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.AbilitiesPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.AbilitiesPacket)
                    .registerServerBoundPacket(0x1d, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.BlockDigPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.BlockDigPacket)
                    .registerServerBoundPacket(0x1e, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.EntityActionPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.EntityActionPacket)
                    .registerServerBoundPacket(0x1f, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.SteerVehiclePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.SteerVehiclePacket)
                    .registerServerBoundPacket(0x20, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.PongPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.PongPacket)
                    .registerServerBoundPacket(0x21, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.RecipeBookPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.RecipeBookPacket)
                    .registerServerBoundPacket(0x22, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.DisplayedRecipePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.DisplayedRecipePacket)
                    .registerServerBoundPacket(0x23, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.NameItemPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.NameItemPacket)
                    .registerServerBoundPacket(0x24, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.ResourcePackReceivePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.ResourcePackReceivePacket)
                    .registerServerBoundPacket(0x25, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.AdvancementTabPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.AdvancementTabPacket)
                    .registerServerBoundPacket(0x26, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.SelectTradePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.SelectTradePacket)
                    .registerServerBoundPacket(0x27, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.SetBeaconEffectPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.SetBeaconEffectPacket)
                    .registerServerBoundPacket(0x28, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.HeldItemSlotPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.HeldItemSlotPacket)
                    .registerServerBoundPacket(0x29, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.UpdateCommandBlockPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.UpdateCommandBlockPacket)
                    .registerServerBoundPacket(0x2a, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.UpdateCommandBlockMinecartPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.UpdateCommandBlockMinecartPacket)
                    .registerServerBoundPacket(0x2b, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.SetCreativeSlotPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.SetCreativeSlotPacket)
                    .registerServerBoundPacket(0x2c, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.UpdateJigsawBlockPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.UpdateJigsawBlockPacket)
                    .registerServerBoundPacket(0x2d, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.UpdateStructureBlockPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.UpdateStructureBlockPacket)
                    .registerServerBoundPacket(0x2e, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.UpdateSignPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.UpdateSignPacket)
                    .registerServerBoundPacket(0x2f, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.ArmAnimationPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.ArmAnimationPacket)
                    .registerServerBoundPacket(0x30, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.SpectatePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.SpectatePacket)
                    .registerServerBoundPacket(0x31, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.BlockPlacePacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.BlockPlacePacket)
                    .registerServerBoundPacket(0x32, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.UseItemPacket::class, io.layercraft.packetlib.packets.v1_19_2.play.serverbound.UseItemPacket),
            )

    val V1_19_3: MinecraftCodec =
        MinecraftCodec.create(ProtocolVersion.V1_19_3)
            .registerPacketRegistry(
                PacketState.HANDSHAKING,
                MinecraftCodecRegistry.create()
                    .registerServerBoundPacket(0x00, io.layercraft.packetlib.packets.v1_19_3.handshaking.serverbound.SetProtocolPacket::class, io.layercraft.packetlib.packets.v1_19_3.handshaking.serverbound.SetProtocolPacket)
                    .registerServerBoundPacket(0xfe, io.layercraft.packetlib.packets.v1_19_3.handshaking.serverbound.LegacyServerListPingPacket::class, io.layercraft.packetlib.packets.v1_19_3.handshaking.serverbound.LegacyServerListPingPacket),
            )
            .registerPacketRegistry(
                PacketState.LOGIN,
                MinecraftCodecRegistry.create()
                    .registerClientBoundPacket(0x00, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.DisconnectPacket::class, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.DisconnectPacket)
                    .registerClientBoundPacket(0x01, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.EncryptionBeginPacket::class, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.EncryptionBeginPacket)
                    .registerClientBoundPacket(0x02, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.SuccessPacket::class, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.SuccessPacket)
                    .registerClientBoundPacket(0x03, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.CompressPacket::class, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.CompressPacket)
                    .registerClientBoundPacket(0x04, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.LoginPluginRequestPacket::class, io.layercraft.packetlib.packets.v1_19_3.login.clientbound.LoginPluginRequestPacket)
                    .registerServerBoundPacket(0x00, io.layercraft.packetlib.packets.v1_19_3.login.serverbound.LoginStartPacket::class, io.layercraft.packetlib.packets.v1_19_3.login.serverbound.LoginStartPacket)
                    .registerServerBoundPacket(0x01, io.layercraft.packetlib.packets.v1_19_3.login.serverbound.EncryptionBeginPacket::class, io.layercraft.packetlib.packets.v1_19_3.login.serverbound.EncryptionBeginPacket)
                    .registerServerBoundPacket(0x02, io.layercraft.packetlib.packets.v1_19_3.login.serverbound.LoginPluginResponsePacket::class, io.layercraft.packetlib.packets.v1_19_3.login.serverbound.LoginPluginResponsePacket),
            )
            .registerPacketRegistry(
                PacketState.STATUS,
                MinecraftCodecRegistry.create()
                    .registerClientBoundPacket(0x00, io.layercraft.packetlib.packets.v1_19_3.status.clientbound.ServerInfoPacket::class, io.layercraft.packetlib.packets.v1_19_3.status.clientbound.ServerInfoPacket)
                    .registerClientBoundPacket(0x01, io.layercraft.packetlib.packets.v1_19_3.status.clientbound.PingPacket::class, io.layercraft.packetlib.packets.v1_19_3.status.clientbound.PingPacket)
                    .registerServerBoundPacket(0x00, io.layercraft.packetlib.packets.v1_19_3.status.serverbound.PingStartPacket::class, io.layercraft.packetlib.packets.v1_19_3.status.serverbound.PingStartPacket)
                    .registerServerBoundPacket(0x01, io.layercraft.packetlib.packets.v1_19_3.status.serverbound.PingPacket::class, io.layercraft.packetlib.packets.v1_19_3.status.serverbound.PingPacket),
            )
            .registerPacketRegistry(
                PacketState.PLAY,
                MinecraftCodecRegistry.create()
                    .registerClientBoundPacket(0x00, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SpawnEntityPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SpawnEntityPacket)
                    .registerClientBoundPacket(0x01, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SpawnEntityExperienceOrbPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SpawnEntityExperienceOrbPacket)
                    .registerClientBoundPacket(0x02, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.NamedEntitySpawnPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.NamedEntitySpawnPacket)
                    .registerClientBoundPacket(0x03, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AnimationPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AnimationPacket)
                    .registerClientBoundPacket(0x04, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.StatisticsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.StatisticsPacket)
                    .registerClientBoundPacket(0x05, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AcknowledgePlayerDiggingPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AcknowledgePlayerDiggingPacket)
                    .registerClientBoundPacket(0x06, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.BlockBreakAnimationPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.BlockBreakAnimationPacket)
                    .registerClientBoundPacket(0x07, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TileEntityDataPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TileEntityDataPacket)
                    .registerClientBoundPacket(0x08, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.BlockActionPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.BlockActionPacket)
                    .registerClientBoundPacket(0x09, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.BlockChangePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.BlockChangePacket)
                    .registerClientBoundPacket(0x0a, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.BossBarPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.BossBarPacket)
                    .registerClientBoundPacket(0x0b, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.DifficultyPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.DifficultyPacket)
                    .registerClientBoundPacket(0x0c, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ClearTitlesPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ClearTitlesPacket)
                    .registerClientBoundPacket(0x0d, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TabCompletePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TabCompletePacket)
                    .registerClientBoundPacket(0x0e, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.DeclareCommandsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.DeclareCommandsPacket)
                    .registerClientBoundPacket(0x0f, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CloseWindowPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CloseWindowPacket)
                    .registerClientBoundPacket(0x10, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WindowItemsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WindowItemsPacket)
                    .registerClientBoundPacket(0x11, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CraftProgressBarPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CraftProgressBarPacket)
                    .registerClientBoundPacket(0x12, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetSlotPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetSlotPacket)
                    .registerClientBoundPacket(0x13, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetCooldownPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetCooldownPacket)
                    .registerClientBoundPacket(0x14, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ChatSuggestionsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ChatSuggestionsPacket)
                    .registerClientBoundPacket(0x15, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CustomPayloadPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CustomPayloadPacket)
                    .registerClientBoundPacket(0x17, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.KickDisconnectPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.KickDisconnectPacket)
                    .registerClientBoundPacket(0x18, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ProfilelessChatPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ProfilelessChatPacket)
                    .registerClientBoundPacket(0x19, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityStatusPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityStatusPacket)
                    .registerClientBoundPacket(0x1a, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ExplosionPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ExplosionPacket)
                    .registerClientBoundPacket(0x1b, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UnloadChunkPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UnloadChunkPacket)
                    .registerClientBoundPacket(0x1c, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.GameStateChangePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.GameStateChangePacket)
                    .registerClientBoundPacket(0x1d, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.OpenHorseWindowPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.OpenHorseWindowPacket)
                    .registerClientBoundPacket(0x1e, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.InitializeWorldBorderPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.InitializeWorldBorderPacket)
                    .registerClientBoundPacket(0x1f, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.KeepAlivePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.KeepAlivePacket)
                    .registerClientBoundPacket(0x20, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.MapChunkPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.MapChunkPacket)
                    .registerClientBoundPacket(0x21, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldEventPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldEventPacket)
                    .registerClientBoundPacket(0x22, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldParticlesPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldParticlesPacket)
                    .registerClientBoundPacket(0x23, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateLightPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateLightPacket)
                    .registerClientBoundPacket(0x24, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.LoginPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.LoginPacket)
                    .registerClientBoundPacket(0x25, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.MapPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.MapPacket)
                    .registerClientBoundPacket(0x26, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TradeListPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TradeListPacket)
                    .registerClientBoundPacket(0x27, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.RelEntityMovePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.RelEntityMovePacket)
                    .registerClientBoundPacket(0x28, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityMoveLookPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityMoveLookPacket)
                    .registerClientBoundPacket(0x29, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityLookPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityLookPacket)
                    .registerClientBoundPacket(0x2a, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.VehicleMovePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.VehicleMovePacket)
                    .registerClientBoundPacket(0x2b, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.OpenBookPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.OpenBookPacket)
                    .registerClientBoundPacket(0x2c, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.OpenWindowPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.OpenWindowPacket)
                    .registerClientBoundPacket(0x2d, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.OpenSignEntityPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.OpenSignEntityPacket)
                    .registerClientBoundPacket(0x2e, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.PingPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.PingPacket)
                    .registerClientBoundPacket(0x2f, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CraftRecipeResponsePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CraftRecipeResponsePacket)
                    .registerClientBoundPacket(0x30, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AbilitiesPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AbilitiesPacket)
                    .registerClientBoundPacket(0x32, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EndCombatEventPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EndCombatEventPacket)
                    .registerClientBoundPacket(0x33, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EnterCombatEventPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EnterCombatEventPacket)
                    .registerClientBoundPacket(0x34, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.DeathCombatEventPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.DeathCombatEventPacket)
                    .registerClientBoundPacket(0x35, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.PlayerRemovePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.PlayerRemovePacket)
                    .registerClientBoundPacket(0x37, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.FacePlayerPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.FacePlayerPacket)
                    .registerClientBoundPacket(0x38, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.PositionPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.PositionPacket)
                    .registerClientBoundPacket(0x39, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UnlockRecipesPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UnlockRecipesPacket)
                    .registerClientBoundPacket(0x3a, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityDestroyPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityDestroyPacket)
                    .registerClientBoundPacket(0x3b, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.RemoveEntityEffectPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.RemoveEntityEffectPacket)
                    .registerClientBoundPacket(0x3c, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ResourcePackSendPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ResourcePackSendPacket)
                    .registerClientBoundPacket(0x3d, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.RespawnPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.RespawnPacket)
                    .registerClientBoundPacket(0x3e, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityHeadRotationPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityHeadRotationPacket)
                    .registerClientBoundPacket(0x3f, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.MultiBlockChangePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.MultiBlockChangePacket)
                    .registerClientBoundPacket(0x40, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SelectAdvancementTabPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SelectAdvancementTabPacket)
                    .registerClientBoundPacket(0x41, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ServerDataPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ServerDataPacket)
                    .registerClientBoundPacket(0x42, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ActionBarPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ActionBarPacket)
                    .registerClientBoundPacket(0x43, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderCenterPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderCenterPacket)
                    .registerClientBoundPacket(0x44, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderLerpSizePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderLerpSizePacket)
                    .registerClientBoundPacket(0x45, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderSizePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderSizePacket)
                    .registerClientBoundPacket(0x46, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderWarningDelayPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderWarningDelayPacket)
                    .registerClientBoundPacket(0x47, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderWarningReachPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.WorldBorderWarningReachPacket)
                    .registerClientBoundPacket(0x48, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CameraPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CameraPacket)
                    .registerClientBoundPacket(0x49, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.HeldItemSlotPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.HeldItemSlotPacket)
                    .registerClientBoundPacket(0x4a, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateViewPositionPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateViewPositionPacket)
                    .registerClientBoundPacket(0x4b, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateViewDistancePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateViewDistancePacket)
                    .registerClientBoundPacket(0x4c, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SpawnPositionPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SpawnPositionPacket)
                    .registerClientBoundPacket(0x4d, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ScoreboardDisplayObjectivePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ScoreboardDisplayObjectivePacket)
                    .registerClientBoundPacket(0x4e, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityMetadataPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityMetadataPacket)
                    .registerClientBoundPacket(0x4f, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AttachEntityPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AttachEntityPacket)
                    .registerClientBoundPacket(0x50, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityVelocityPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityVelocityPacket)
                    .registerClientBoundPacket(0x51, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityEquipmentPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityEquipmentPacket)
                    .registerClientBoundPacket(0x52, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ExperiencePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ExperiencePacket)
                    .registerClientBoundPacket(0x53, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateHealthPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateHealthPacket)
                    .registerClientBoundPacket(0x54, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ScoreboardObjectivePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ScoreboardObjectivePacket)
                    .registerClientBoundPacket(0x55, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetPassengersPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetPassengersPacket)
                    .registerClientBoundPacket(0x56, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TeamsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TeamsPacket)
                    .registerClientBoundPacket(0x57, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ScoreboardScorePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.ScoreboardScorePacket)
                    .registerClientBoundPacket(0x58, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SimulationDistancePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SimulationDistancePacket)
                    .registerClientBoundPacket(0x59, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetTitleSubtitlePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetTitleSubtitlePacket)
                    .registerClientBoundPacket(0x5a, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateTimePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.UpdateTimePacket)
                    .registerClientBoundPacket(0x5b, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetTitleTextPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetTitleTextPacket)
                    .registerClientBoundPacket(0x5c, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetTitleTimePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SetTitleTimePacket)
                    .registerClientBoundPacket(0x5d, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntitySoundEffectPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntitySoundEffectPacket)
                    .registerClientBoundPacket(0x5e, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SoundEffectPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SoundEffectPacket)
                    .registerClientBoundPacket(0x5f, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.StopSoundPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.StopSoundPacket)
                    .registerClientBoundPacket(0x60, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SystemChatPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.SystemChatPacket)
                    .registerClientBoundPacket(0x61, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.PlayerlistHeaderPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.PlayerlistHeaderPacket)
                    .registerClientBoundPacket(0x62, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.NbtQueryResponsePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.NbtQueryResponsePacket)
                    .registerClientBoundPacket(0x63, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CollectPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.CollectPacket)
                    .registerClientBoundPacket(0x64, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityTeleportPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityTeleportPacket)
                    .registerClientBoundPacket(0x65, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AdvancementsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.AdvancementsPacket)
                    .registerClientBoundPacket(0x66, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityUpdateAttributesPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityUpdateAttributesPacket)
                    .registerClientBoundPacket(0x67, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.FeatureFlagsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.FeatureFlagsPacket)
                    .registerClientBoundPacket(0x68, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityEffectPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.EntityEffectPacket)
                    .registerClientBoundPacket(0x6a, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TagsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.clientbound.TagsPacket)
                    .registerServerBoundPacket(0x00, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.TeleportConfirmPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.TeleportConfirmPacket)
                    .registerServerBoundPacket(0x01, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.QueryBlockNbtPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.QueryBlockNbtPacket)
                    .registerServerBoundPacket(0x02, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SetDifficultyPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SetDifficultyPacket)
                    .registerServerBoundPacket(0x03, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.MessageAcknowledgementPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.MessageAcknowledgementPacket)
                    .registerServerBoundPacket(0x06, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.ClientCommandPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.ClientCommandPacket)
                    .registerServerBoundPacket(0x07, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SettingsPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SettingsPacket)
                    .registerServerBoundPacket(0x08, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.TabCompletePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.TabCompletePacket)
                    .registerServerBoundPacket(0x09, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.EnchantItemPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.EnchantItemPacket)
                    .registerServerBoundPacket(0x0a, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.WindowClickPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.WindowClickPacket)
                    .registerServerBoundPacket(0x0b, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.CloseWindowPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.CloseWindowPacket)
                    .registerServerBoundPacket(0x0c, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.CustomPayloadPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.CustomPayloadPacket)
                    .registerServerBoundPacket(0x0d, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.EditBookPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.EditBookPacket)
                    .registerServerBoundPacket(0x0e, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.QueryEntityNbtPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.QueryEntityNbtPacket)
                    .registerServerBoundPacket(0x0f, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UseEntityPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UseEntityPacket)
                    .registerServerBoundPacket(0x10, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.GenerateStructurePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.GenerateStructurePacket)
                    .registerServerBoundPacket(0x11, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.KeepAlivePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.KeepAlivePacket)
                    .registerServerBoundPacket(0x12, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.LockDifficultyPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.LockDifficultyPacket)
                    .registerServerBoundPacket(0x13, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.PositionPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.PositionPacket)
                    .registerServerBoundPacket(0x14, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.PositionLookPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.PositionLookPacket)
                    .registerServerBoundPacket(0x15, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.LookPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.LookPacket)
                    .registerServerBoundPacket(0x16, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.FlyingPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.FlyingPacket)
                    .registerServerBoundPacket(0x17, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.VehicleMovePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.VehicleMovePacket)
                    .registerServerBoundPacket(0x18, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SteerBoatPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SteerBoatPacket)
                    .registerServerBoundPacket(0x19, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.PickItemPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.PickItemPacket)
                    .registerServerBoundPacket(0x1a, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.CraftRecipeRequestPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.CraftRecipeRequestPacket)
                    .registerServerBoundPacket(0x1b, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.AbilitiesPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.AbilitiesPacket)
                    .registerServerBoundPacket(0x1c, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.BlockDigPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.BlockDigPacket)
                    .registerServerBoundPacket(0x1d, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.EntityActionPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.EntityActionPacket)
                    .registerServerBoundPacket(0x1e, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SteerVehiclePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SteerVehiclePacket)
                    .registerServerBoundPacket(0x1f, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.PongPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.PongPacket)
                    .registerServerBoundPacket(0x20, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SessionPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SessionPacket)
                    .registerServerBoundPacket(0x21, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.RecipeBookPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.RecipeBookPacket)
                    .registerServerBoundPacket(0x22, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.DisplayedRecipePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.DisplayedRecipePacket)
                    .registerServerBoundPacket(0x23, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.NameItemPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.NameItemPacket)
                    .registerServerBoundPacket(0x24, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.ResourcePackReceivePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.ResourcePackReceivePacket)
                    .registerServerBoundPacket(0x25, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.AdvancementTabPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.AdvancementTabPacket)
                    .registerServerBoundPacket(0x26, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SelectTradePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SelectTradePacket)
                    .registerServerBoundPacket(0x27, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SetBeaconEffectPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SetBeaconEffectPacket)
                    .registerServerBoundPacket(0x28, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.HeldItemSlotPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.HeldItemSlotPacket)
                    .registerServerBoundPacket(0x29, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateCommandBlockPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateCommandBlockPacket)
                    .registerServerBoundPacket(0x2a, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateCommandBlockMinecartPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateCommandBlockMinecartPacket)
                    .registerServerBoundPacket(0x2b, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SetCreativeSlotPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SetCreativeSlotPacket)
                    .registerServerBoundPacket(0x2c, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateJigsawBlockPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateJigsawBlockPacket)
                    .registerServerBoundPacket(0x2d, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateStructureBlockPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateStructureBlockPacket)
                    .registerServerBoundPacket(0x2e, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateSignPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UpdateSignPacket)
                    .registerServerBoundPacket(0x2f, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.ArmAnimationPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.ArmAnimationPacket)
                    .registerServerBoundPacket(0x30, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SpectatePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.SpectatePacket)
                    .registerServerBoundPacket(0x31, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.BlockPlacePacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.BlockPlacePacket)
                    .registerServerBoundPacket(0x32, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UseItemPacket::class, io.layercraft.packetlib.packets.v1_19_3.play.serverbound.UseItemPacket),
            )

    val V1_19_4: MinecraftCodec = this.V1_19_3.copy(ProtocolVersion.V1_19_4)
}