package io.layercraft.translator.packets.server.login

import io.layercraft.translator.*
import kotlinx.serialization.Serializable

/**
 * Encryption request | client-bound | Packet ID 0x01 | State: Login | Answer with [EncryptionResponse].
 *
 * @property serverId Appears to be empty.
 * @property publicKey The server's public key, in bytes. Length before as a VarInt.
 * @property verifyToken A sequence of random bytes generated by the server. Length before as a VarInt.
 * @see <a href="https://wiki.vg/Protocol#Encryption_Request">https://wiki.vg/Protocol#Encryption_Request</a>
 */
@Serializable
data class EncryptionRequest(
    @MinecraftString(20)
    val serverId: String,
    @MinecraftArray(MinecraftArraySizeType.VARINT)
    val publicKey: ByteArray,
    @MinecraftArray(MinecraftArraySizeType.VARINT)
    val verifyToken: ByteArray
)
