name: Gradle Publish

on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions: write-all

jobs:
  publish-github:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: 'gradle'

      - name: Test with Gradle
        run: ./gradlew test
        env:
          USERNAME: ${{ github.repository_owner }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: ./gradlew publish -Dorg.gradle.project.version=${{ github.event.release.tag_name }}
        env:
          USERNAME: ${{ github.repository_owner }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            commitMode: true # remove later when the translation api is finished

      - name: Upload a Build Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          body: ${{steps.github_release.outputs.changelog}}


